variable "region" {
  description = "The AWS region to use"
  default     = "us-east-1"
}

variable "availability_zone_a" {
  default = "us-east-1a"
}

variable "availability_zone_b" {
  default = "us-east-1b"
}


# https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Subnets.html#vpc-subnet-basics
#
# To add a CIDR block to your VPC, the following rules apply:
# ...
# The CIDR block must not be the same or larger than the CIDR range of a route
# in any of the VPC route tables. For example, if you have a route with a
# destination of 10.0.0.0/24 to a virtual private gateway, you cannot associate
# a CIDR block of the same range or larger. However, you can associate a CIDR
# block of 10.0.0.0/25 or smaller.

variable "vpc_cidr_block" {
  type    = "string"
  default = "10.0.0.0/24"
}

variable "public_cidr_block" {
  type    = "string"
  default = "10.0.0.128/25"
}

variable "private_cidr_block_a" {
  type    = "string"
  default = "10.0.0.64/26"
}

variable "private_cidr_block_b" {
  type    = "string"
  default = "10.0.0.0/26"
}

variable "tags" {
  type        = "map"
  description = "Resource tags"
  default     = {}
}

variable "rds_snapshot_id" {
  description = "Name of the DB snapshot that's used to restore the DB instance"
  default     = ""
}

variable "rds_master_user_password" {
  description = "Password for the master DB user"
  default     = ""  # will be autogenerated if left blank
}

variable "app_server_instance_type" {
  default = "m3.medium"
}

variable "app_server_key_pair_name" {
  description = "Name of the key pair to use for the app server instance"
}

variable "app_server_ssh_users" {
  type        = "list"
  description = "Github usernames to be allowed SSH access to the app server instance"
  default     = []
}

variable "git_commit" {
  description = "Github repo code commit to use for deployment"
  default     = ""
}

variable "django_admin_password" {
  description = "Password for Django superuser"
  default     = ""  # will be autogenerated if left blank
}

variable "django_default_from_email" {
  description = "Default email address to use for various automated correspondence from the site manager(s)"
  default     = "webmaster@localhost"
}

variable "django_server_email" {
  description = "Email address that error messages come from"
  default     = "root@localhost"
}

variable "django_admin_email" {
  description = "Email address for code error notifications (full exception information)"
  default     = ""
}

variable "site_name" {
  description = "Name of the site (cannot contain apostrophes)"
  default = "Refinery Platform"
}

variable "site_domain" {
  description = "Host name of the site"
  default = "www.example.org"
}

variable "tls" {
  description = "Whether or not to use TLS to serve the site (true or false)"
  default = "true"
}
